version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    expose:
      - "9000"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: perpusgul.mysql.database.azure.com
      DB_PORT: 3306
      DB_DATABASE: perpus
      DB_USERNAME: rrjzuvhxsk
      DB_PASSWORD: Qw9oYbDRajMjS$Kk
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # Optional: hanya gunakan jika butuh DB lokal
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: perpus
      MYSQL_ROOT_PASSWORD: Qw9oYbDRajMjS$Kk
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    # ports:
    #   - "3306:3306"  # Enable only if needed

volumes:
  dbdata:

networks:
  laravel:
