services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: perpus
      DB_USERNAME: rrjzuvhxsk
      DB_PASSWORD: Qw9oYbDRajMjS$Kk

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: perpus
      MYSQL_ROOT_PASSWORD: 12345678
