version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: perpus
      DB_USERNAME: rrjzuvhxsk
      DB_PASSWORD: Qw9oYbDRajMjS$Kk

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: perpus
      MYSQL_ROOT_PASSWORD: Qw9oYbDRajMjS$Kk
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
